language: node_js
node_js:
- '9'
cache:
  directories:
  - node_modules

install: npm install

stages:
  - check
  - deploy

jobs:
  fast_finish: true
  include:
    - name: lint
      stage: check
      script:
        - npm run lint:config:strict
        - npm run lint:strict
    - name: build
      stage: check
      script: npm run build

    - name: deploy to staging
      stage: deploy
      if: type = push AND branch = master
      script: BUILD_ENV='"staging"' npm run build
      deploy:
        - provider: pages
          repo: test-fajnie-ze-wiesz/test-fajnie-ze-wiesz.github.io
          fqdn: test-app.fajniezewiesz.pl
          skip_cleanup: true
          keep_history: false
          target_branch: master
          local_dir: dist/
          github_token: $GITHUB_TOKEN
          on:
            branch: master

    - name: deploy to production
      stage: deploy
      if: type = push AND branch = production
      script: npm run build
      deploy:
        - provider: pages
          repo: fajnie-ze-wiesz/fajnie-ze-wiesz.github.io
          fqdn: aplikacja.fajniezewiesz.pl
          skip_cleanup: true
          keep_history: false
          target_branch: master
          local_dir: dist/
          github_token: $GITHUB_TOKEN
          on:
            branch: production

notifications:
  email:
    on_success: never
    on_failure: always
