language: node_js
node_js:
- '9'
cache:
  directories:
  - node_modules
install:
- "./.travis/install.sh"
script:
- "./.travis/run.sh"
deploy:
  - provider: pages
    skip-cleanup: true
    keep-history: false
    repo: fajnie-ze-wiesz/fajnie-ze-wiesz.github.io
    target-branch: master
    local-dir: dist/
    github-token: $GITHUB_TOKEN
    on:
      branch: master
  - provider: pages
    skip-cleanup: true
    keep-history: false
    repo: fajnie-ze-wiesz/test.app.fajniezewiesz.pl
    target-branch: master
    local-dir: dist/
    github-token: $GITHUB_TOKEN
    on:
      branch: master
  - provider: pages
    skip-cleanup: true
    keep-history: false
    repo: fajnie-ze-wiesz/app.fajniezewiesz.pl
    target-branch: master
    local-dir: dist/
    github-token: $GITHUB_TOKEN
    on:
      branch: production
