language: node_js
node_js:
- '12'
cache:
  directories:
  - node_modules
install:
- "./.travis/install.sh"
script:
- "./.travis/run.sh"
deploy:
  - provider: pages
    repo: test-fajnie-ze-wiesz/test-fajnie-ze-wiesz.github.io
    fqdn: test-app.fajniezewiesz.com.pl
    skip-cleanup: true
    keep-history: false
    target-branch: master
    local-dir: dist/
    github-token: $GITHUB_TOKEN
    on:
      branch: master
  - provider: pages
    repo: fajnie-ze-wiesz/fajnie-ze-wiesz.github.io
    fqdn: aplikacja.fajniezewiesz.com.pl
    skip-cleanup: true
    keep-history: false
    target-branch: master
    local-dir: dist/
    github-token: $GITHUB_TOKEN
    on:
      branch: production
